### ISSUE TITLE
师傅部分检测不出来

### ISSUE THREAD

**Issue by xkhl-yyds** [Jun-5heng/Struts2_Scan#1]
![image](https://user-images.githubusercontent.com/83859223/171087401-2ce42498-29b1-4ee5-a308-f549da6c8ec7.png)
![image](https://user-images.githubusercontent.com/83859223/171087465-6a507b6f-f9ba-40b1-8c90-edf89190f271.png)
![image](https://user-images.githubusercontent.com/83859223/171087491-50fae960-1ca4-431e-b53e-3e80062e38d4.png)
师傅检测不到S2-059  61 62

**Comment by Jun-5heng** [comment]
> ![图片](https://user-images.githubusercontent.com/83859223/171087401-2ce42498-29b1-4ee5-a308-f549da6c8ec7.png) ![图片](https://user-images.githubusercontent.com/83859223/171087465-6a507b6f-f9ba-40b1-8c90-edf89190f271.png) ![图片](https://user-images.githubusercontent.com/83859223/171087491-50fae960-1ca4-431e-b53e-3e80062e38d4.png) 师傅检测不到 S2-059 61 62

你使用的是哪个docker环境？我之前在测试利用类的时候是全部都可以的

**Comment by xkhl-yyds** [comment]
用的vulfocus的，

**Comment by Jun-5heng** [comment]
> 用的vulfocus的，

给一下docker名称吧，docker pull能拉吗？

**Comment by xkhl-yyds** [comment]
> > 用的vulfocus的，
> 
> 给一下docker名称吧，docker pull能拉吗？
用的这个靶场
https://fofapro.github.io/vulfocus/#/INSTALL
![image](https://user-images.githubusercontent.com/83859223/171136650-554b7bc1-d277-4596-8e23-5aed68c013be.png)

**Comment by Jun-5heng** [comment]
> > > 用的vulfocus的，
> > 
> > 
> > 给一下docker名称吧，docker pull能拉吗？
> > 用的这个靶场
> > https://fofapro.github.io/vulfocus/#/INSTALL
> > ![image](https://user-images.githubusercontent.com/83859223/171136650-554b7bc1-d277-4596-8e23-5aed68c013be.png)

我先看看  稍后给你回复吧

**Comment by Jun-5heng** [comment]
> > > 用的vulfocus的，
> > 
> > 
> > 给一下docker名称吧，docker pull能拉吗？
> > 用的这个靶场
> > https://fofapro.github.io/vulfocus/#/INSTALL
> > ![image](https://user-images.githubusercontent.com/83859223/171136650-554b7bc1-d277-4596-8e23-5aed68c013be.png)

059已经修改了，注意利用时提交的参数，默认为“id”，但并不是所有的站点都是“id”这个参数，还有就是url地址问题要准确。因为源码并没有打包，你可以对利用类进行单独测试，剩下的061、062你可以再进行确认看是否是利用类的问题，如果是利用类的问题，稍后附带利用环境可以再回复我

**Comment by xkhl-yyds** [comment]
> 

![image](https://user-images.githubusercontent.com/83859223/171183963-0db1e452-f829-41c2-a8cf-1e0309ab7e0c.png)
师傅参数是这样提交的嘛

**Comment by Jun-5heng** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/83859223/171183963-0db1e452-f829-41c2-a8cf-1e0309ab7e0c.png)
> 师傅参数是这样提交的嘛

这个参数要配合具体的漏洞去使用，如果是扫描填充参数很有可能报错退出，后续这个我看情况优化吧

**Comment by xkhl-yyds** [comment]
> 



> > > 
> > 
> > 
> > ![图像](https://user-images.githubusercontent.com/83859223/171183963-0db1e452-f829-41c2-a8cf-1e0309ab7e0c.png)师傅参数是这样提交的嘛
> 
> 这个参数要配合具体的漏洞去使用，如果是扫描填充参数很有可能报错退出，后续这个我看情况优化吧

![image](https://user-images.githubusercontent.com/83859223/171189018-3aa5ffbc-1c21-42a0-b5c9-a2606c3b22c7.png)
S2-059提交参数后识别错了

**Comment by Jun-5heng** [comment]
> > 
> 
> > > > 
> > > 
> > > 
> > > ![图像](https://user-images.githubusercontent.com/83859223/171183963-0db1e452-f829-41c2-a8cf-1e0309ab7e0c.png)师傅参数是这样提交的嘛
> > 
> > 
> > 这个参数要配合具体的漏洞去使用，如果是扫描填充参数很有可能报错退出，后续这个我看情况优化吧
> 
> ![image](https://user-images.githubusercontent.com/83859223/171189018-3aa5ffbc-1c21-42a0-b5c9-a2606c3b22c7.png) S2-059提交参数后识别错了

已修改，如果有其他问题可以继续反馈

**Comment by xkhl-yyds** [comment]
用的vulfocus的，不知道为啥就是不能成功





君昊Yosel
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Jun-5heng/Struts2_Scan"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月31日(星期二) 下午2:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Jun-5heng/Struts2_Scan] 师傅部分检测不出来 (Issue #1)





  
   师傅检测不到 S2-059 61 62
  
你使用的是哪个docker环境？我之前在测试利用类的时候是全部都可以的

**Comment by Jun-5heng** [comment]
> 用的vulfocus的，不知道为啥就是不能成功 君昊Yosel ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Jun-5heng/Struts2_Scan" ***@***.***&gt;; 发送时间:&nbsp;2022年5月31日(星期二) 下午2:59 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Jun-5heng/Struts2_Scan] 师傅部分检测不出来 (Issue #1) 师傅检测不到 S2-059 61 62 你使用的是哪个docker环境？我之前在测试利用类的时候是全部都可以的 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

哪个漏洞？
