### ISSUE TITLE
现在我遇到了一个新问题

### ISSUE THREAD

**Issue by SecureKaiser** [Jun-5heng/Struts2_Scan#5]
![图片](https://user-images.githubusercontent.com/104421343/173198001-2ed85dde-4904-4efa-b26d-0658b43e5735.png)

**Comment by Jun-5heng** [comment]
> ![图片](https://user-images.githubusercontent.com/104421343/173198001-2ed85dde-4904-4efa-b26d-0658b43e5735.png)

![image](https://user-images.githubusercontent.com/88525975/173198492-ad3c60c6-0f7a-4e28-902c-96d71113d2ca.png)

**Comment by SecureKaiser** [comment]
红队能用吗  马上就去市红护网

**Comment by Jun-5heng** [comment]
> 红队能用吗 马上就去市红护网

![image](https://user-images.githubusercontent.com/88525975/173198999-d3bbb383-30c1-4e41-a2d1-55ba9c158d24.png)
