### ISSUE TITLE
文件呢

### ISSUE THREAD

**Issue by ewfubwefwe** [Jun-5heng/Struts2_Scan#8]
文件呢

**Comment by Jun-5heng** [comment]
没有文件（狗头）

**Comment by Jun-5heng** [comment]
> 文件呢

没有文件（狗头）

**Comment by ewfubwefwe** [comment]
发一下微信，我加你



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月8日(周五) 下午2:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jun-5heng/Struts2_Scan] 文件呢 (Issue #8)




 
没有文件（狗头）

**Comment by ewfubwefwe** [comment]
你好微信可以发一下吗我发文件给你



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月8日(周五) 下午2:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jun-5heng/Struts2_Scan] 文件呢 (Issue #8)




 
Closed #8 as completed.

**Comment by Jun-5heng** [comment]
> 你好微信可以发一下吗我发文件给你
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年7月8日(周五) 下午2:57 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [Jun-5heng/Struts2_Scan] 文件呢 (Issue #8) Closed #8 as completed. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

发文件给我？打算钓我鱼是吧
